### PR TITLE
UNICODE BUG FIX

### PR DESCRIPTION
**Pull request by KSTARK007**
len(link)>128 error(unicode) handled 
auto download all torrents(1080p)[as per requirements of user] in a single run if unavailable then downloads 720p .
none exit bug fixed.
parse tree error fixed in requirements

### CODE REVIEW

**Comment by KSTARK007** [comment]
Updated downloadable + updated data + unavailable data handled

**Comment by KSTARK007** [comment]
Keeping it to a minimal

**Comment by makkoncept** [comment]
hi @kiranthecoder, thanks for the PR. I had my endsem exams so I was not able to address this.
The script uses python 3.x. For the sake of consistency can you please use `print()` instead of `print`.
I will merge this.

**Comment by KSTARK007** [comment]
@makkoncept done thank you for your time

**Pull request merged**
